Hao's code smells fixes
anthonyliuhao/cs361_group_project pull request #30
Opened 2020-11-21 18:11 UTC by anthonyliuhao

My refactoring is focused on the Build a Recipe feature and view. By extracting common table manipulation code (such as `createRow`, `createTextOnlyCell`, and `createButtonCell`) into a stand alone `TableBuilder` class, the changes help reduce length of the `loadPageContent` method of the client class `BuildRecipeViewController`.

The changes primarily address the Long Method and Large Class code smells.

2020-11-22 03:30 UTC, alexlo510 approved these changes

2020-11-22 05:28 UTC, anjelbenitez approved these changes

2020-11-22 11:47 UTC, hermancai requested changes
The infoButton eventListener in BuildRecipeViewController.js is very different in the [branch I'm working on](https://github.com/anthonyliuhao/cs361_group_project/blob/herman-code-smells/public/js/build/BuildRecipeViewController.js) because it includes the 'replace ingredient' feature, which has not been merged into development.

2020-11-22 19:57 UTC, anthonyliuhao commented
> The infoButton eventListener in BuildRecipeViewController.js is very different in the [branch I'm working on](https://github.com/anthonyliuhao/cs361_group_project/blob/herman-code-smells/public/js/build/BuildRecipeViewController.js) because it includes the 'replace ingredient' feature, which has not been merged into development.

@hermancai I thought your changes have been merged. When do you think you will be able to post a PR?

2020-11-23 01:50 UTC, hermancai approved these changes

2020-11-23 02:09 UTC, merged