Refactor ingredient info
anthonyliuhao/cs361_group_project pull request #48
Opened 2020-11-28 02:04 UTC by hermancai

This branch refactors the 'getIngredientInfo' route into multiple routes (getEthicalProblem, getEthicalDescription, getAlternatives).

2020-11-28 23:58 UTC, anthonyliuhao submitted a review, later dismissed

2020-11-29 18:35 UTC, alexlo510 approved these changes, later dismissed
nice work Herman

2020-11-29 21:13 UTC, anthonyliuhao requested changes
I just realized how we had completely different ideas in mind when we talked about making the ethical issues more obvious.

Would it be possible to implement it so that there is a warning icon next to every ingredient with an ethical issue? When the user hovers over the icon, a tooltip is displayed with a description of the ethical issue.
![Blank diagram](https://user-images.githubusercontent.com/26575820/100553757-8a09e000-3244-11eb-841b-4d90bcad011a.png)

The current design is a little overwhelming. An Abi or Pat will feel obligated to read everything before they do anything. This goes against the following.
> Heuristic #3 (of 9): Let people gather as much information as they want, and no more than they want

2020-11-29 21:13 UTC, anthonyliuhao commented on main.js
> +              order by i.name asc`,
It is a little confusing that the ethical issue column is sorted by ingredient name but the ingredient list itself is not sorted.

2020-11-30 02:52 UTC, anjelbenitez approved these changes
Looks good!

2020-11-30 03:07 UTC, anthonyliuhao approved these changes
Great work. Thanks @hermancai !

2020-11-30 03:08 UTC, merged